version: "3.5"
services:
  pg:
    image: postgres:11.5-alpine
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=300'
    volumes:
      - pgdata:/var/lib/postgresql/data:delegated
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_USER=$PGUSER
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 60s
      timeout: 60s
      retries: 3

  redis:
    image: redis:5.0-alpine
    # command: redis-server --requirepass pass
    volumes:
      - redisdata:/data:delegated
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
