env:
  ENTERPRISE: '1'
  DOCKER_BUILDKIT: '1'
  FORCE_COLOR: '3'
  GO111MODULE: 'on'
  IMAGE: 'server_instrumented'
  TAG: '${BUILDKITE_BUILD_NUMBER}_${BUILDKITE_RETRY_COUNT}'
  COVERAGE_INSTRUMENT: 'true'
  VAGRANT_RUN_ENV: 'CI'

steps:
  - label: ':docker::arrow_right::chromium:'
    agents:
      queue: 'baremetal'
    commands:
      - cd /sourcegraph
      - ./test/e2e/test.sh
    plugins:
      - ssh://git@github.com/sourcegraph/vagrant-buildkite-plugin.git#fix/pwd:
          box: sourcegraph-e2e
          workdir: test
          plugins:
            - vagrant-google
            - vagrant-env
            - vagrant-scp
